# Generated by Django 5.2.17 on 2026-08-11 19:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartCalculationVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("contract_version", models.CharField(max_length=32)),
                ("adapter_version", models.CharField(max_length=64)),
                ("provider", models.CharField(max_length=32)),
                ("provider_api_version", models.CharField(max_length=32)),
                ("timezone_data_version", models.CharField(max_length=32)),
                ("geonames_dataset_version", models.CharField(max_length=64)),
                ("zodiac_system", models.CharField(max_length=32)),
                ("house_system", models.CharField(max_length=32)),
                ("aspect_profile_version", models.CharField(max_length=64)),
                ("application_git_sha", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BirthProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("display_label", models.CharField(max_length=120)),
                ("local_birth_date", models.DateField()),
                ("local_birth_time", models.TimeField(blank=True, null=True)),
                (
                    "birth_time_precision",
                    models.CharField(
                        choices=[("EXACT", "EXACT"), ("UNKNOWN", "UNKNOWN")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="birth_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="birth_profiles",
                        to="locations.resolvedlocation",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="NatalChart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("input_snapshot", models.JSONField()),
                ("input_fingerprint", models.CharField(db_index=True, max_length=64)),
                ("normalized_result", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCEEDED", "Succeeded"), ("FAILED", "Failed")], max_length=16
                    ),
                ),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("failure_message", models.CharField(blank=True, max_length=240)),
                ("provider_response_hash", models.CharField(blank=True, max_length=64)),
                ("calculated_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "birth_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charts",
                        to="charts.birthprofile",
                    ),
                ),
                (
                    "calculation_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charts",
                        to="charts.chartcalculationversion",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="natal_charts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charts",
                        to="locations.resolvedlocation",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["owner", "-created_at"], name="chart_owner_created")
                ],
            },
        ),
    ]
