# Generated by Django 5.2.17 on 2026-08-11 19:10

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


def enable_pg_trgm(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunPython(enable_pg_trgm, migrations.RunPython.noop),
        migrations.CreateModel(
            name="GeoNamesDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.CharField(max_length=64, unique=True)),
                ("source_name", models.CharField(default="GeoNames cities500", max_length=64)),
                ("source_modified_at", models.DateTimeField(blank=True, null=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("row_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ResolvedLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source", models.CharField(max_length=32)),
                ("source_id", models.CharField(max_length=64)),
                ("selected_display_name", models.CharField(max_length=400)),
                ("locality", models.CharField(max_length=200)),
                ("admin_region", models.CharField(blank=True, max_length=200)),
                ("country_name", models.CharField(max_length=200)),
                ("country_code", models.CharField(max_length=2)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("timezone_id", models.CharField(max_length=64)),
                ("source_data_version", models.CharField(max_length=64)),
                ("resolved_at", models.DateTimeField(auto_now_add=True)),
                ("identity_hash", models.CharField(editable=False, max_length=64, unique=True)),
            ],
            options={
                "ordering": ("selected_display_name",),
            },
        ),
        migrations.CreateModel(
            name="GeoNameLocation",
            fields=[
                ("geonames_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("canonical_name", models.CharField(max_length=200)),
                ("ascii_name", models.CharField(max_length=200)),
                ("search_name", models.TextField()),
                ("country_code", models.CharField(max_length=2)),
                ("country_name", models.CharField(blank=True, max_length=200)),
                ("admin1_code", models.CharField(blank=True, max_length=20)),
                ("admin1_name", models.CharField(blank=True, max_length=200)),
                ("admin2_code", models.CharField(blank=True, max_length=80)),
                ("admin2_name", models.CharField(blank=True, max_length=200)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("population", models.BigIntegerField(default=0)),
                ("feature_class", models.CharField(max_length=1)),
                ("feature_code", models.CharField(max_length=10)),
                ("timezone_id", models.CharField(max_length=64)),
                ("source_modified_on", models.DateField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="locations.geonamesdataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeoNameAlternateName",
            fields=[
                ("alternate_name_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("iso_language", models.CharField(blank=True, max_length=16)),
                ("name", models.CharField(max_length=400)),
                ("search_name", models.TextField()),
                ("is_preferred", models.BooleanField(default=False)),
                ("is_short", models.BooleanField(default=False)),
                ("is_colloquial", models.BooleanField(default=False)),
                ("is_historic", models.BooleanField(default=False)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternate_names",
                        to="locations.geonamelocation",
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_name"],
                        name="alternate_name_trgm",
                        opclasses=["gin_trgm_ops"],
                    ),
                    models.Index(
                        fields=["location", "-is_preferred"], name="alternate_location_pref"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="geonamelocation",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_name"], name="location_name_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="geonamelocation",
            index=models.Index(fields=["country_code", "-population"], name="location_country_pop"),
        ),
        migrations.AddIndex(
            model_name="geonamelocation",
            index=models.Index(
                fields=["country_code", "admin1_code"], name="location_country_admin"
            ),
        ),
    ]
